site_name: Docs                                 # Название вашего сайта (отображается в шапке)
site_url: https://your-site.com                 # Базовый URL для production-сборки
site_description: "Документация к проекту"      # Мета-описание
site_author: "GiBi The Developer of this site"  # Автор (для мета-тегов)
copyright: "© 2025 GiBi"                        # Текст в подвале сайта

theme:
  name: material                # Обязательно для Material темы
  language: ru                  # Язык интерфейса (ru/en/es и др.)

  # Цветовая схема
  palette:
    - scheme: default                 # Светлая тема
      toggle:
        icon: material/weather-sunny  # Иконка переключения
        name: Светлая тема            # Текст для переключения
      primary: deep purple            # Основной цвет
      accent: light blue              # Акцентный цвет

    - scheme: slate                   # Тёмная тема
      toggle:
        icon: material/weather-night
        name: Тёмная тема
      primary: deep purple
      accent: light blue

  # Функции темы
  features:
    - navigation.tabs           # Вкладки в навигации
    - navigation.top            # Кнопка "Наверх"
    - navigation.sections       # Иерархия разделов
    - navigation.indexes        # Индексные страницы
    - content.tabs.link         # Табы для контента

  # Шрифты
  font:
    text: Roboto                # Основной шрифт
    code: JetBrains Mono        # Шрифт для кода

  # Иконки
  icon:
    repo: fontawesome/brands/git-alt  # Иконка репозитория

nav:
  - Главная: index.md # Простой пункт меню
  - Руководства:      # Выпадающий раздел
      - "Установка": guides/installation.md
      - "Настройка": guides/configuration.md
  - API:
      - "Справочник": "api/reference.md" # Ссылка на файл
      - "Примеры": "api/examples.md"

plugins:
  - search:
      lang: ru
      separator: '[\s\-\.]+'
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: True
      baselevel: 2
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
      use_pygments: true
      pygments_style: monokai
  - footnotes
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list

docs_dir: /vault                # Папка с исходными .md файлами
site_dir: /site                 # Папка для сгенерированного сайта
use_directory_urls: true        # ЧПУ (site/page вместо site/page.html)

extra:                          # Дополнительные параметры
  social:                       # Соцсети в подвале
    - icon: fontawesome/brands/github
      link: https://github.com/yourname
    - icon: fontawesome/brands/telegram
      link: https://t.me/GiBiFoR

extra_javascript:
  - https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js